# Generated by Django 4.2.1 on 2023-05-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_name_delete_part_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='price',
            field=models.FloatField(),
        ),
    ]
