# Generated by Django 4.2.1 on 2023-05-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_name_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categories')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.name')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.part')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categories')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.name')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.part')),
            ],
        ),
    ]
