# Generated by Django 4.2.1 on 2023-05-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_logs_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
