# Generated by Django 4.2.1 on 2023-05-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_logs_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
