# Generated by Django 4.2.1 on 2023-05-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_name_price_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='part',
        ),
        migrations.RemoveField(
            model_name='log',
            name='category',
        ),
        migrations.RemoveField(
            model_name='log',
            name='name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='part',
        ),
        migrations.RemoveField(
            model_name='name',
            name='part',
        ),
        migrations.RemoveField(
            model_name='part',
            name='category',
        ),
        migrations.RemoveField(
            model_name='price',
            name='part',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
