# Generated by Django 4.2.1 on 2023-05-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='part',
            new_name='name',
        ),
    ]
