# Generated by Django 4.2.1 on 2023-05-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='name',
            name='category',
        ),
        migrations.RemoveField(
            model_name='name',
            name='part',
        ),
        migrations.RemoveField(
            model_name='part',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
