# Generated by Django 4.2.1 on 2023-05-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
