# Generated by Django 4.2.1 on 2023-05-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_inventory_name_alter_log_name_alter_name_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='part',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
