# Generated by Django 4.2.1 on 2023-05-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='type',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='type',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='type',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='type',
            new_name='sub_category',
        ),
    ]
