# Generated by Django 4.2.1 on 2023-05-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_type_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
