# Generated by Django 4.2.1 on 2023-05-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_sub_category_inventory_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='part',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
