# Generated by Django 4.2.1 on 2023-05-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_part_inventory_name_rename_part_log_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='log',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='part',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
