# Generated by Django 4.2.1 on 2023-05-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_log_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='time',
            new_name='date',
        ),
    ]
